FROM golang:1.21.9 as builder
WORKDIR /app
RUN git clone https://github.com/wormhole-foundation/wormhole.git
WORKDIR /app/wormhole
RUN cd tools && go mod download
RUN make node

FROM ubuntu:latest
COPY --from=builder /app/wormhole/build/bin/guardiand /guardiand
RUN setcap cap_ipc_lock=+ep /guardiand
# ENTRYPOINT ["/guardiand"]
